# Generated by Django 5.2.17 on 2026-09-02 11:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('number', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9A-F]{3}$', 'Use three uppercase hexadecimal digits.')])),
                ('slug', models.SlugField(unique=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('blurb', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=200)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reading', 'Reading'), ('interactive', 'Interactive')], max_length=11)),
                ('title', models.CharField(max_length=200)),
                ('content', models.JSONField(default=dict)),
                ('world', models.JSONField(blank=True, default=dict)),
                ('base_revision', models.CharField(blank=True, max_length=3, validators=[django.core.validators.RegexValidator('^[0-9A-F]{3}$', 'Use three uppercase hexadecimal digits.')])),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='curriculum.challenge')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChallengeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reading', 'Reading'), ('interactive', 'Interactive')], max_length=11)),
                ('title', models.CharField(max_length=200)),
                ('content', models.JSONField(default=dict)),
                ('world', models.JSONField(blank=True, default=dict)),
                ('revision', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[0-9A-F]{3}$', 'Use three uppercase hexadecimal digits.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='curriculum.challenge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['challenge_id', '-revision'],
            },
        ),
        migrations.CreateModel(
            name='ContentRelease',
            fields=[
                ('release_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph', models.JSONField(default=dict)),
                ('manifest', models.JSONField(default=dict)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('graph', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.challenge')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_entries', to='curriculum.contentrelease')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.challengerevision')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.topic')),
            ],
            options={
                'ordering': ['topic__display_order', 'display_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='challengerevision',
            constraint=models.UniqueConstraint(fields=('challenge', 'revision'), name='unique_challenge_revision'),
        ),
        migrations.AddConstraint(
            model_name='releasechallenge',
            constraint=models.UniqueConstraint(fields=('release', 'challenge'), name='one_revision_per_challenge_per_release'),
        ),
    ]
