// GENERATED by tools/generate.py — do not edit by hand.
// PW[n][i]: password yielded by level n, variant i (unlocks level n+1).
export const PW = [
  ["9SRYYAyYPYCNaBe5", "gBERT5zWu9Y7WbaX", "65PdtLnrtqCrV6kP", "ZcGj84Yn6htyHCdL", "uCfgLeFvUNF5KsNm", "tLBzz5weqBREJX8T", "uxs2Ns25S5mpPGrV", "b6muPyhJEyDtzxPB", "kSwDdmjF5Z8eB4C9", "K7uucy6SmD5N7gYB", "wUCLJ8DN8p8zf6Ex", "gKvP7V8AYWaEhW94"],
  ["K9bxZKr7hx4jaNuJ", "2n8TuEkzdEfFuUAQ", "pVVwebMEdFUGJC8u", "magPnQZSvrAyNTHU", "6RDK3w92Vhxp4TwJ", "fuf7UMFS2aMkC8kW", "rgHeb2HyagTdJdu5", "hMnpXadda8VbgJbu", "G62YgHhAePrKF8ae", "VdFZj9wvaayQ43Lv", "gUE5TzGsbe5nkEbx", "BD722DqNTP5tnrqD"],
  ["VnkEQnvSpQm5WJKj", "aFPVbwW3pudD8H7x", "sxJuMkWkvRTxXnBx", "7VbadVB5NDpfSDve", "ePcmSUqzK2Rvsa4X", "akwjnFUgFPMLzWaB", "Ctrr2WYVvWpAvL3S", "KCgGjYeXcE8Za8fR", "z5JC5m3abSDLRmDH", "A3fjUqShBmvwxEk7", "h49CS2Qnet7uNwUu", "zaxQNxCyfmZsVJmb"],
  ["g3ewBZAwMJX4nGx6", "yJ76Xs7f6x2mftbv", "3HneChXezMWA47UL", "hzBepKzaxTkQ8sCT", "Evns6nQW5HJqcLZf", "rW4eTYgu6jZfv2de", "h4M2TbwxMV9yxKSc", "bTeTCTY7dp3jcNbU", "9KcUDF8RKa9LRjGu", "QmXWmu2gyYjjMPkx", "qESue8CKVE3ggLkG", "3yuF6uKVVa4fgGUm"],
  ["bfFL8gZgNZPasDqm", "t5AmfMZwzRryNHXD", "qvcQzyxPFqFM76fs", "HE9fz5fgL57kyrUy", "STa7y68mtDU3MshS", "hLhtGrdgkLNPETUJ", "nVNXnPtTc5B4MdZh", "3jw6hWx7qZjDdTXb", "cf8S763TK6D6Nu39", "y6rBNh6rbUQGwHjY", "7K6wTpq85AF4GAJd", "B9mgUjMv2wrTaVgv"],
  ["3S6GKUhQZBrYRAR2", "8jytDbFakFQUYgPZ", "WFgENFhPcVvYrbpy", "vazgg36gDR2qNnHA", "hTwsEBhc3fJWxeHT", "HHnjQvRENB6y4Bsc", "5cTMUSFcv5u4JBxN", "9ABPgADwkEKFwAcT", "JSytp7brJM7rRNbF", "SvqvECx49uy8YynQ", "9TX2f7cpyhpv5mBz", "jSs8uzZHzgjcWC83"],
  ["tM88yCSfw9MC6Rk6", "8fUqDAC9nXBVTMeq", "3umSfacPGdqJpvzc", "VGYVG39fBEhxgSAE", "6CeTrqUE9Fc7G6WA", "7tYJLrQh8NhJfuvq", "Je8cKZGEFBSvqaJJ", "8hN5cdGDQ8zP7mtU", "eJfMFA9a7HFt5JAy", "Kg2SY27akNyMCXKF", "9pvxcLUhvmVYwKeh", "RkqHYrhUeaExGY5y"],
  ["ewtCaYUcE4jLutWX", "MUNkT7anSL8HsHj5", "DGr8qjGW4EG89hSG", "hACzt9WpRsHSLgNT", "XDuRgrggHK7BtXsf", "h8BStYk788p4Yr9g", "AFXb3xeTAnLHxBHd", "NLd3vt9K5k7gAxqh", "uRuV5Z6GxSyYkhYL", "PCVeDXFzXHRFx9Bw", "hCRdRvNLwp3C3KTS", "zQm8JaEcQ43rqqc4"],
  ["Fn4Nv5UqGpU4UcSz", "BxfrY5XKRqMLX6fN", "qzV8PeVELg8L6Lkq", "ScckKB7qjtQZTfuJ", "V5w2jgHCq9DRrXxX", "addu6uU4ucvHmWgc", "VqNtVyX7277MXjdV", "L8suBaupZsjkVZfv", "xrkPkWQMZ7nPec7z", "EhJTmsbQBLQxfdH8", "ecWVk7TDSLCVjjHe", "waaHS9nRStT9jAgK"],
  ["SAWJJN9q8aDGjQBv", "g4ZRpfBbmfNtP2vq", "kXubzQax6429SWZd", "fJaAs9drqcmRfmyf", "ApVhUjya82ySQn33", "gJFXBcWgYNurMuua", "AqhDFwmwxWTEkg6U", "LgGuncvqBQ5cjUrG", "yc6Gaac7Njnhzd8C", "gPH9ERyzr5Bmv9Yq", "RwUr3MN4VLQMvQQW", "DNkKN6G5BSSSC7kG"],
  ["Rer3zv2d8Vj3SZan", "JFtnmft8mZcsY3yn", "sZ97cYhxdkQp2BMF", "wFbabAtJUWM4XZ34", "nXNVkvNUPbqsjFvT", "Q2jyQuuqgXsyLufb", "tmfdQmgXY5FsGKvK", "EdWPbF5cj8Cuzga7", "EJkn7sG47BxBWgSy", "W4cuXGvbVXWZwtNj", "REqF3dVH5ZaaCx3c", "YezPUsZVCtj5tmAq"],
  ["8Sp6NfXVGVDceLUG", "fG42dK3KDkA2Nfc5", "JQvZPKRzB8dYs9TA", "2uZK4SF5WMKBFk9U", "sCxZE2SxmwhQzdHb", "dD79VUkwnN8Hk56Z", "JLcwYSBZR4Me6u2P", "jV3QfJ8BFKVngjpU", "frvnYYGthJ3GAt8f", "rCYP3v22T5PvbZvn", "cQr45B95FpUp9bUC", "YTmeBjTXgLX2YJgK"],
  ["mYvUaN6tbwatHuHN", "ZRLbxWUW8u3ZwqKd", "etCNeh72tXnvkr94", "76wPDPJG4t9yyM5q", "LAAaTkCXFMazKAUr", "LjzXeW72QMbZrUpm", "RkhWxA8B9G3dDb2L", "AbGzS4dt3sdtYNYR", "bTRKdzvgR74hK8sG", "KWypGUwY9j77EHLV", "gHQSdj83bJEZAuGJ", "A5t82VAkpCtkSwFq"],
  ["CSdn9ANpYnfKD22c", "EHRx7fmAPGGTBnKr", "q2K9VVpUAUGFJ4Mr", "uJeHbeLUrbtZQfRB", "NM6Laa2nM5dXr5AW", "nes2EhA22shKZKLD", "Cg3TLjMxVak4NS8S", "YMGB9G8x4CrtECxX", "Ua4CjDXkaCDJQabU", "tahLUeuWKMK7c4JC", "Zhf74FwLQ4GShEKE", "t6dhtvpbdYdTbCkw"],
  ["YgTAxvXctFAm8bfT", "7kKMgEU2WAzzTp6N", "7mkREuXRm4bmybWS", "CzkKy7BKZFk7UC2T", "wHrD6fRSUV6brpDZ", "6wPTN9mn4AwLNAHL", "tUWGLB275EFG3U39", "2TQyKjezqLLz69hh", "nT9TusFsEGFAErkN", "J9j578H6Q3DPaxCk", "6LNs6mmxT9U592jM", "yNANqyC9EratgZDB"],
  ["QzNSKbfuT5Wpfx3W", "rLhDSCkx2sZdwqZb", "ZvPHHVCCsAZGYQDn", "QQ5N8HVmvzGyuDMX", "V27V2MUmS3vaQjrb", "YJYMLg9gpcSS2kFg", "GqjueRbVBp9Rxp6T", "4c7JtLWgHQeWpeyc", "t6rHfYYQnBqNqWUP", "fUq6GWMdC7qz8UgD", "LX2TGVuhRsAxRnB7", "Q9KX8ZJPdwaPP4h4"],
  ["wfWPWEA5cgPvP7Kn", "MRqkWRztQRytB5x4", "LHZ6rvt7mqPrFLPt", "9Ewhx4K72b5zFCWJ", "ESfY8QejR677Eq7T", "S2tTcQECHRSXZyNj", "2CxdjCqz8Cuqq8B7", "CUpu7NySpAsESEsF", "3QsnSZjajjd7rQUJ", "KyCsSzexRZJdGd7t", "7ua7dBZfqE2rAtmr", "fE6CT79wBRuRFQ9U"],
  ["3GPwFLve4cWP7CNT", "M6MYGPZHB4TZbsw4", "rT3XUJy4ecARSSaT", "yFGpXvRhs5NSTtJW", "Mqu4h26G5B3UPu7Z", "ErZ8TmkY4Vr7vZCW", "mgLLKJaxKgCjrPvv", "SMW7RDV3jASdKJNt", "5d9bANDJhsJNCGN4", "reMsLzm2cx6rvuar", "r7kXjM4RbutrKvFc", "rCH2hfKb2maFPBk8"],
  ["wk9nMcvzCjkmJzHU", "59tQKGVT6Z8MYEAT", "yKfKmWk9NM2PdbZQ", "f7zHLL3VMzrSQ9gU", "Nyx4fmgzT4EBVKMw", "CSQHJqNQ3arf7xTB", "VdmngeZyLZUwdHNg", "yDzhrDQuQxFsVLQL", "Dbarv5rRK8buyRT8", "J4bqDaCw97jNHcAC", "3Ej6Ga5ZjH9ncweb", "jbqpHScfwqT5snHD"],
  ["HxbddZDUaUrG37qu", "LgmGw95676VWg6vY", "6eJN4Sx6sZwgwyS5", "awjbMQbV5CuaYDV9", "TtjCRPPHk6AwZJ3H", "vrEGEsEBjEHGzLNb", "qhLwQcwB2fj3qeej", "fyNkTR5C52f95NVe", "6TMQcXfXrfUYcJQu", "KuhtR9hZuxkwdgyE", "kVSqR4W4VRNx8GUK", "CLYDkG8Cf9jgJ6GE"],
  ["cdqpefQyuBRn3Y8S", "f5DX5RPQQngjU2Gv", "mazTnLtFmnTSgKuA", "zfMNDAhFJHkWFmna", "AGkYMKMqqQEfaPcR", "eNSXhe43M2WjppqB", "EFq7EJxwDYLNtBKG", "acEmhDChujExgJUP", "MJTJPXZUUDX4EYMZ", "AaRqG9trE9npzRKF", "aTrR8ahs73Zy8pgC", "UHgP5YNW4dBgQaud"],
  ["vTzhu4WNGuXhetfq", "T3RhKexFADySqsGw", "PrCYP2BRqVugLTB5", "8XxZYpKHZGUt6s7v", "9nvWatb2TnbxTrWy", "jVBC3ECS2QLKrE3G", "wVYKzFTdZatxgXhA", "KkLeDAmwemKkAjdK", "8Tyj9LTE8fcrvnrA", "9PW2rLVMYEGXzFaZ", "aprxR9cjQt6tGkbP", "CLVKpPEqmPddDEYJ"],
  ["f9LHK8Wd2T9ZBHYb", "9CVL4wNQTMGcmgjM", "Pdxfn68hdqGyBHDD", "zvAUmQaqx9a7D2RB", "ncfDGSnJjHENxXpF", "SLURmgP3tzVyFpr2", "ycNuLmhFH2b5rXP7", "mLq4LxQrA7HTLDXZ", "YQ467KecUvBXFQvC", "msz7Tm7gYeNL5P8c", "34SUseK8BFh84GEc", "KJsZxtGkML7eFHeB"],
  ["3BC6t98PcUWRre5Q", "FgvytU8DwagaqhLt", "vrYmBeQUmnKxCf7v", "EbS4npAZnKGmuFrv", "uvwacXCMgJ8vejnF", "9fyGrGDEBRpz7X6B", "5M3gaudBJsmQsd3X", "e37aAFVgKhH85SFS", "hhzapDBq6DuJfqJn", "kKZ934b3VsThKwPX", "UEkpeGLZ4U55VFyS", "78MWYQyjQLVNXZws"],
  ["dQzxNpLcyw9EKvWM", "eSsWV7khfmQVwSEp", "wK2vKt4LxRmrRMCE", "5hrVYwCbb4tn9VCp", "96653tz5cuUH7eLE", "8vWwFYdRtMfBu4KH", "rVVxbeWqJDuZxTMF", "cPgWxLj6RnZxUvXe", "bSe2JF2wfHuXTj6j", "2UBJraULwpREpeyD", "Y6bnhRTdCvFWdz4e", "D7KKCkhXsDBfEymS"],
];

export const DATA = {
  "ports": [
    2049,
    6817,
    6818,
    9100,
    51820,
    3000,
    9090,
    20049,
    111,
    8889,
    9093,
    6819
  ],
  "ips": [
    "10.100.50.10",
    "10.100.50.1",
    "10.100.50.254",
    "10.100.50.100",
    "10.100.50.5",
    "10.100.50.2",
    "10.100.50.20",
    "10.100.50.11",
    "10.100.50.9",
    "10.100.50.250",
    "10.100.50.3",
    "10.100.50.12"
  ],
  "nfsOpts": [
    "no_root_squash",
    "insecure",
    "anonuid=0",
    "no_root_squash",
    "insecure",
    "anonuid=0",
    "no_root_squash",
    "insecure",
    "anonuid=0",
    "no_root_squash",
    "insecure",
    "anonuid=0"
  ],
  "hpl": [
    {
      "nodes": 2,
      "mem": 4,
      "nb": 192,
      "n": 29184
    },
    {
      "nodes": 2,
      "mem": 4,
      "nb": 256,
      "n": 29184
    },
    {
      "nodes": 2,
      "mem": 8,
      "nb": 192,
      "n": 41280
    },
    {
      "nodes": 2,
      "mem": 8,
      "nb": 256,
      "n": 41216
    },
    {
      "nodes": 2,
      "mem": 16,
      "nb": 192,
      "n": 58560
    },
    {
      "nodes": 2,
      "mem": 16,
      "nb": 256,
      "n": 58368
    },
    {
      "nodes": 4,
      "mem": 4,
      "nb": 192,
      "n": 41280
    },
    {
      "nodes": 4,
      "mem": 4,
      "nb": 256,
      "n": 41216
    },
    {
      "nodes": 4,
      "mem": 8,
      "nb": 192,
      "n": 58560
    },
    {
      "nodes": 4,
      "mem": 8,
      "nb": 256,
      "n": 58368
    },
    {
      "nodes": 4,
      "mem": 16,
      "nb": 192,
      "n": 82752
    },
    {
      "nodes": 4,
      "mem": 16,
      "nb": 256,
      "n": 82688
    }
  ],
  "grid": [
    {
      "ranks": 8,
      "cores": 4,
      "ghz": 2.5,
      "p": 2,
      "q": 4,
      "pass": "2x4-160"
    },
    {
      "ranks": 8,
      "cores": 8,
      "ghz": 2.5,
      "p": 2,
      "q": 4,
      "pass": "2x4-320"
    },
    {
      "ranks": 8,
      "cores": 4,
      "ghz": 3.0,
      "p": 2,
      "q": 4,
      "pass": "2x4-192"
    },
    {
      "ranks": 8,
      "cores": 8,
      "ghz": 3.0,
      "p": 2,
      "q": 4,
      "pass": "2x4-384"
    },
    {
      "ranks": 16,
      "cores": 4,
      "ghz": 2.5,
      "p": 4,
      "q": 4,
      "pass": "4x4-160"
    },
    {
      "ranks": 16,
      "cores": 8,
      "ghz": 2.5,
      "p": 4,
      "q": 4,
      "pass": "4x4-320"
    },
    {
      "ranks": 16,
      "cores": 4,
      "ghz": 3.0,
      "p": 4,
      "q": 4,
      "pass": "4x4-192"
    },
    {
      "ranks": 16,
      "cores": 8,
      "ghz": 3.0,
      "p": 4,
      "q": 4,
      "pass": "4x4-384"
    },
    {
      "ranks": 32,
      "cores": 4,
      "ghz": 2.5,
      "p": 4,
      "q": 8,
      "pass": "4x8-160"
    },
    {
      "ranks": 32,
      "cores": 8,
      "ghz": 2.5,
      "p": 4,
      "q": 8,
      "pass": "4x8-320"
    },
    {
      "ranks": 32,
      "cores": 4,
      "ghz": 3.0,
      "p": 4,
      "q": 8,
      "pass": "4x8-192"
    },
    {
      "ranks": 32,
      "cores": 8,
      "ghz": 3.0,
      "p": 4,
      "q": 8,
      "pass": "4x8-384"
    }
  ],
  "flags": [
    "UWC_HPC{8mbrBGgp2nhJ}",
    "UWC_HPC{L7ZADuycD5ts}",
    "UWC_HPC{GEpUR3Xngan2}",
    "UWC_HPC{jgYrLKhbwvkp}",
    "UWC_HPC{wduyFsRU7xfc}",
    "UWC_HPC{Arp7JdShaZEh}",
    "UWC_HPC{cWf6v7V9gNk7}",
    "UWC_HPC{s65wrfXtAJv8}",
    "UWC_HPC{cXnPE7suMeR9}",
    "UWC_HPC{dfvaDBQv8ZYL}",
    "UWC_HPC{wmuEqgsCV8Sd}",
    "UWC_HPC{CSd48vTEJnu4}"
  ]
};
