#!/usr/bin/env python3
"""Generate js/levels/gen-data.js (per-variant passwords + answer data) and
js/levels/hashes.js (SHA-256 gate table). Single source of truth: the yielded
password of level N (any variant) must unlock level N+1, so both files come
from one run of this script.

Run from the repo root:  python3 tools/generate.py
"""

import hashlib
import json
import math
import os
import secrets

ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789"
NLEVELS = 25
NVARIANTS = 12


def pw(length=16):
    return "".join(secrets.choice(ALPHABET) for _ in range(length))


def sha(s):
    return hashlib.sha256(s.encode()).hexdigest()


# Random passwords for every level/variant (answer-levels override below).
PW = [[pw() for _ in range(NVARIANTS)] for _ in range(NLEVELS)]

# Level 16: password = the blocked port number (cluster services).
PORTS = [2049, 6817, 6818, 9100, 51820, 3000, 9090, 20049, 111, 8889, 9093, 6819]

# Level 17: password = the head node's IP (what chrony.conf should point at).
IPS = [f"10.100.50.{o}" for o in (10, 1, 254, 100, 5, 2, 20, 11, 9, 250, 3, 12)]

# Level 18: password = the dangerous export option.
NFS_OPTS = ["no_root_squash", "insecure", "anonuid=0"] * 4

# Level 22: password = HPL problem size N.
#   N = floor(sqrt(0.8 * nodes * mem_bytes / 8) / NB) * NB
HPL = []
for nodes in (2, 4):
    for mem in (4, 8, 16):
        for nb in (192, 256):
            raw = math.sqrt(0.8 * nodes * mem * 2**30 / 8)
            n = int(raw // nb) * nb
            HPL.append({"nodes": nodes, "mem": mem, "nb": nb, "n": n})
assert len(HPL) == NVARIANTS

# Level 23: password = "PxQ-RPeak" for the given ranks and node CPU.
GRIDS = {8: (2, 4), 16: (4, 4), 32: (4, 8)}
GRID = []
for ranks in (8, 16, 32):
    for cores, ghz in ((4, 2.5), (8, 2.5), (4, 3.0), (8, 3.0)):
        p, q = GRIDS[ranks]
        rpeak = int(cores * ghz * 16)
        GRID.append({"ranks": ranks, "cores": cores, "ghz": ghz,
                     "p": p, "q": q, "pass": f"{p}x{q}-{rpeak}"})
assert len(GRID) == NVARIANTS

# Level 24: password = the flag.
FLAGS = ["UWC_HPC{%s}" % pw(12) for _ in range(NVARIANTS)]

# What each level yields (unlocks level n+1)
def yielded(n):
    if n == 16:
        return [str(p) for p in PORTS]
    if n == 17:
        return IPS
    if n == 18:
        return NFS_OPTS
    if n == 22:
        return [str(v["n"]) for v in HPL]
    if n == 23:
        return [v["pass"] for v in GRID]
    if n == 24:
        return FLAGS
    return PW[n]


root = os.path.join(os.path.dirname(__file__), "..")

with open(os.path.join(root, "js/levels/gen-data.js"), "w") as f:
    f.write("// GENERATED by tools/generate.py — do not edit by hand.\n")
    f.write("// PW[n][i]: password yielded by level n, variant i (unlocks level n+1).\n")
    f.write("export const PW = [\n")
    for row in PW:
        f.write("  " + json.dumps(row) + ",\n")
    f.write("];\n\n")
    f.write("export const DATA = " + json.dumps({
        "ports": PORTS,
        "ips": IPS,
        "nfsOpts": NFS_OPTS,
        "hpl": HPL,
        "grid": GRID,
        "flags": FLAGS,
    }, indent=2) + ";\n")

with open(os.path.join(root, "js/levels/hashes.js"), "w") as f:
    f.write("// GENERATED by tools/generate.py — do not edit by hand.\n")
    f.write("// GATE[n]: accepted SHA-256 hashes to unlock level n (= hashes of\n")
    f.write("// every variant password yielded by level n-1). Level 0 is open.\n")
    f.write("export const GATE = {\n")
    # GATE[25] validates the final flag (level 24 yields it; nothing to unlock).
    for n in range(1, NLEVELS + 1):
        hashes = sorted(set(sha(p) for p in yielded(n - 1)))
        f.write(f"  {n}: " + json.dumps(hashes) + ",\n")
    f.write("};\n")

print(f"generated gen-data.js and hashes.js ({NLEVELS} levels x {NVARIANTS} variants)")
